import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../store";
import { Group } from "@/interfaces/task";

export interface Groups {
    [key: string]: Group;
  };
const initialState: Groups = {
  "sample_group_1": {
    name: "To Do",
    color: "red",
    tasks: [
      "task_1"
    ],
  },
  "sample_group_2": {
    name: "Doing",
    color: "green",
    tasks: [
      "task_2"
    ],
  },
  "sample_group_3": {
    name: "Done",
    color: "blue",
    tasks: [
      "task_3"
    ],
  }
};

export const GroupSlice = createSlice({
  name: "projects",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setGroup: (state, action: PayloadAction<[string, Group]>) => {
      action.payload[0] in state ? state[action.payload[0]] = action.payload[1] : null
    },
    addGroup: (state, action: PayloadAction<[string, string, string]>) => {
      state[action.payload[0]] = {
          name: action.payload[1],
          color: action.payload[2],
          tasks: [
          ],
      }
      console.log("Group", state)
    },
    removeGroup: (state, action: PayloadAction<string>) => {
      delete state[action.payload]
    },
    setTasks: (state, action: PayloadAction<[string, string[]]>) => {
      action.payload[0] in state ? state[action.payload[0]].tasks = action.payload[1] : null
    },
    addTaskToGroup: (state, action: PayloadAction<[string, string]>) => {
      action.payload[0] in state ? state[action.payload[0]].tasks.push(action.payload[1]) : null
    },
    setGroupColor: (state, action: PayloadAction<[string, string]>) => {
      action.payload[0] in state ? state[action.payload[0]].color = action.payload[1] : null
    },
    removeTaskFromGroup: (state, action: PayloadAction<[string, string]>) => {
      if (action.payload[0] in state.boards) {
        let temp = state[action.payload[0]].tasks
        let ind = temp.indexOf(action.payload[1])
        temp.splice(ind)
      }
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const {
  setGroup,
  addGroup,
  removeGroup,
  setTasks,
  addTaskToGroup,
  setGroupColor,
  removeTaskFromGroup
} = GroupSlice.actions;
export const selectGroups = (state: RootState) => state.groups;

export default GroupSlice.reducer;
