import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../store";

export interface State {
  modal: string | null;
}

const initialState: State = {
  modal: null,
};

export const StateSlice = createSlice({
  name: "state",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setModal: (state, action: PayloadAction<string>) => {
      state.modal = action.payload;
    },
    closeModal: (state) => {
      state.modal = null;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

export const {
  setModal,
  closeModal,
} = StateSlice.actions;
export const selectModal = (state: RootState) => state.state.modal;

export default StateSlice.reducer;
